[workspace]
members = [
    "raytracer",
    "chapter02",
    "chapter04",
    "chapter05",
    "chapter06",
    "chapter07",
    "chapter08",
    "chapter09",
    "chapter10",
    "chapter11",
    ]

[workspace.dependencies]
image = "0.24"
